# Generated by Django 6.0.3 on 2026-03-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='priority',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('normal', 'Normal')], default='normal', max_length=20),
        ),
    ]
