# Generated by Django 6.0.3 on 2026-03-20 04:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_patient_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pharmacy_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='triage_started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
