# Generated by Django 6.0.3 on 2026-03-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_gynecologyconsultation_obstetricconsultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='associated_symptoms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='chronic_illnesses',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='current_medications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='drug_allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='family_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='follow_up_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='food_allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='health_conditions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='consultation',
            name='hospitalizations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='consultation',
            name='illness_location',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='illness_onset',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='illness_severity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='consultation',
            name='medication_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='on_medication',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='consultation',
            name='recommendations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='significant_infections',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='surgeries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='consultation',
            name='systems_cardiovascular',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='systems_gastrointestinal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='systems_heent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='systems_musculoskeletal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='systems_neurological',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='systems_respiratory',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='doctor_notes',
            field=models.TextField(blank=True),
        ),
    ]
